### ISSUE TITLE
Ignore KronDelta when reparam=False

### ISSUE THREAD

**Issue by ssanner** [pyrddlgym-project/pyRDDLGym-symbolic#5]
Domains with only Bernoulli and KronDelta (such as Navigation) should compile to XADDs without reparameterization (reparam=False).

This should be a simple fix for the compiler to ignore KronDelta (now deprecated and not required) during compilation.

**Comment by jihwan-jeong** [comment]
Closing as Commit 4dc3861 fixes this.
